### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by josalmi**

### CODE REVIEW

**Comment by Kauhsa** [comment]
:+1:

**Comment by vforteli** [comment]
I think I may be a bit too biased to merge this one

**Comment by Kauhsa** [comment]
I'm a bit worried about an accurate representation of a seagull here. Can you test it pls

**Comment by vforteli** [comment]
Hmm, regarding testing the accuracy of the representation.
I thought we could upload the icon somewhere public, and let google index it. If it turns up when searching for seagulls and then similar pictures it should prove its accurate

**Pull request closed without merging**
