### PR TITLE
New icons and new style

### PR DESCRIPTION
**Pull request by josalmi**

### CODE REVIEW

**Comment by Kauhsa** [comment]
We iterated this a bit (should show here as well if Joni merges): https://github.com/josalmi/lokki-android/pull/1/files

**Comment by Kauhsa** [comment]
Login screen still has the old logo :( Also is the navigation bar a bit too bright now? It could also be that I'm just too used to the old one.

**Comment by josalmi** [comment]
Current color is http://www.google.com/design/spec/style/color.html#color-color-palette light blue 500.
We could change it to blue 500. @Kauhsa are you able to test and take a pictures for comparison?

**Comment by Kauhsa** [comment]
Yeah, I'll do it after lunch.

**Comment by Kauhsa** [comment]
Light Blue 500 (current one in this PR):
lokki1

Blue 500:
lokki2

...not really a big difference... as a bonus, Light Blue 700:

lokki3

**Comment by Kauhsa** [comment]
Gonna copy the screens here from the other pr:

lokki1
lokki2

**Pull request merged**
