### PR TITLE
Made UI more clear in situation when there is no addable contacts

### PR DESCRIPTION
**Pull request by Grandi**
Attempts to fix the search box issue mentioned in https://github.com/TheSoftwareFactory/lokki-android/issues/22#issuecomment-70623504

### CODE REVIEW

**Comment by Grandi** [comment]
rerun this please

**Comment by Grandi** [comment]
rerun tests please

**Comment by Grandi** [comment]
retest this please

**Comment by Grandi** [comment]
retest this please

**Comment by newa34** [comment]
Not able to add my own email but whitespace after email address is treating it as new email and allow to add.

**Comment by Grandi** [comment]
retest this please

**Comment by newa34** [comment]
it working fine now.

**Pull request merged**
