### PR TITLE
Place adding tip & Buzz settings remain after renaming

### PR DESCRIPTION
**Pull request by Grandi**
See https://github.com/TheSoftwareFactory/lokki-android/issues/320
and https://github.com/TheSoftwareFactory/lokki-android/issues/316

### CODE REVIEW

**Comment by Grandi** [comment]
retest this please

**Comment by newa34** [comment]
Tip text is invisible on another map mode except Default

**Comment by Grandi** [comment]
Strange, for me it's visible in all map modes.

**Comment by Grandi** [comment]
retest this please

**Comment by Grandi** [comment]
retest this please

**Pull request merged**
