### PR TITLE
Delete a place by long pressing place image, not text

### PR DESCRIPTION
**Pull request by akiratk0355**
This work connects to #21.
It doesn't enable swiping, but might be useful than before.

### CODE REVIEW

**Comment by vforteli** [comment]
The problem is the contact avatars are drawn over the background so only the lower edge of the background image will be long clickable. Tried this?

**Comment by Kauhsa** [comment]
Does this still retain the ability to click on text too?

**Comment by akiratk0355** [comment]
@vforteli It didn't happen to me. In what case were contact avatars drawn over it?

@Kauhsa In this change texts are not clickable anymore, but it can be easily retained.

**Comment by vforteli** [comment]
@akiratk0355 I tried something similar, but could be i had the longclick handler on some other object, maybe directly on the resource

**Comment by akiratk0355** [comment]
@vforteli I see. I didn't notice it. So that case should be tested.

**Pull request closed without merging**
