### PR TITLE
Suppressed unnecessary warnings

### PR DESCRIPTION
**Pull request by Grandi**

### CODE REVIEW

**Comment by eemihauk** [comment]
Have you tried to suppress warnings just in `LokkiBaseTest` to avoid the need to repeat the suppress annotation in multiple places?

**Comment by Grandi** [comment]
At least AndroidStudio doesn't seem to recognize the suppression if the annotation is only located in LokkiBaseTest.

**Comment by newa34** [comment]
Adding Suppress warning only on LokkiBaseTest worked.

**Comment by Grandi** [comment]
Closing this pull request since no-one is going to merge it. Git doesn't allow me to have two pull requests at the same time.

**Pull request closed without merging**
